import React, { useState } from 'react'
import {
  Download,
  FileText,
  TrendingUp,
  Users,
  Camera,
  Briefcase,
  Clock,
  MoreVertical,
  Trash2,
  X,
} from 'lucide-react'
import { cn } from '../../utils'
import { useStore } from '../../store/AppStore'

const reportTypes = [
  {
    title: 'Revenue Report',
    description: 'Monthly revenue breakdown by client, project, and revenue stream with YTD comparisons.',
    icon: TrendingUp,
    iconBg: 'bg-emerald-50',
    iconColor: 'text-emerald-600',
    format: 'PDF',
  },
  {
    title: 'Expense Report',
    description: 'Detailed expense categorization with department-level spend analysis and budget comparisons.',
    icon: FileText,
    iconBg: 'bg-rose-50',
    iconColor: 'text-rose-600',
    format: 'CSV',
  },
  {
    title: 'Team Performance',
    description: 'Team utilization rates, project completion metrics, and individual productivity scores.',
    icon: Users,
    iconBg: 'bg-blue-50',
    iconColor: 'text-blue-600',
    format: 'PDF',
  },
  {
    title: 'Equipment Utilization',
    description: 'Equipment usage rates, maintenance schedules, and availability forecasts.',
    icon: Camera,
    iconBg: 'bg-amber-50',
    iconColor: 'text-amber-600',
    format: 'PDF',
  },
  {
    title: 'Project Summary',
    description: 'Comprehensive project status report including timelines, budgets, and milestone tracking.',
    icon: Briefcase,
    iconBg: 'bg-indigo-50',
    iconColor: 'text-indigo-600',
    format: 'CSV',
  },
]

interface RecentReport {
  id: number; type: string; date: string; generatedBy: string; status: string; format: string
}

let nextId = 1

export function AdminReports() {
  const { projects, invoices, expenses, equipment, teamMembers, tasks } = useStore()
  const [recentReports, setRecentReports] = useState<RecentReport[]>([])
  const [openMenuId, setOpenMenuId] = useState<number | null>(null)
  const [showGenerate, setShowGenerate] = useState(false)

  const handleDelete = (id: number) => {
    setOpenMenuId(null)
    if (confirm('Are you sure you want to delete this report?')) {
      setRecentReports(prev => prev.filter(r => r.id !== id))
    }
  }

  const generateReport = (type: string) => {
    const rtype = reportTypes.find(r => r.title === type) || reportTypes[0]
    const now = new Date()
    const dateStr = now.toLocaleDateString('en-US', { month: 'short', day: '2-digit', year: 'numeric' })
    const newReport: RecentReport = {
      id: nextId++,
      type: rtype.title,
      date: dateStr,
      generatedBy: 'Current User',
      status: 'Generated',
      format: rtype.format,
    }
    setRecentReports(prev => [newReport, ...prev])
    setShowGenerate(false)
  }

  const handleDownload = (report: RecentReport) => {
    const lines = [
      `${report.type}`,
      `Generated: ${report.date}`,
      `Generated By: ${report.generatedBy}`,
      `${'='.repeat(40)}`,
      '',
    ]
    switch (report.type) {
      case 'Revenue Report':
        lines.push('INVOICES:')
        invoices.forEach(i => lines.push(`  ${i.id} | ${i.client} | $${i.amount.toLocaleString()} | ${i.status} | Due: ${i.dueDate}`))
        lines.push('')
        lines.push(`Total Invoiced: $${invoices.reduce((s, i) => s + i.amount, 0).toLocaleString()}`)
        lines.push(`Total Paid: $${invoices.filter(i => i.status === 'Paid').reduce((s, i) => s + i.amount, 0).toLocaleString()}`)
        lines.push(`Total Pending: $${invoices.filter(i => i.status === 'Pending').reduce((s, i) => s + i.amount, 0).toLocaleString()}`)
        lines.push(`Total Overdue: $${invoices.filter(i => i.status === 'Overdue').reduce((s, i) => s + i.amount, 0).toLocaleString()}`)
        break
      case 'Expense Report':
        lines.push('EXPENSES:')
        expenses.forEach(e => lines.push(`  ${e.description} | ${e.department} | $${e.amount.toLocaleString()} | ${e.status} | ${e.requestedBy}`))
        lines.push('')
        lines.push(`Total Expenses: $${expenses.reduce((s, e) => s + e.amount, 0).toLocaleString()}`)
        lines.push(`Approved: $${expenses.filter(e => e.status === 'Approved').reduce((s, e) => s + e.amount, 0).toLocaleString()}`)
        lines.push(`Pending: $${expenses.filter(e => e.status === 'Pending').reduce((s, e) => s + e.amount, 0).toLocaleString()}`)
        break
      case 'Team Performance':
        lines.push('TEAM MEMBERS:')
        teamMembers.forEach(t => lines.push(`  ${t.name} | ${t.role} | ${t.project} | ${t.status} | Tasks: ${t.tasks} | Availability: ${t.availability}%`))
        lines.push('')
        lines.push('TASKS:')
        tasks.forEach(t => lines.push(`  ${t.title} | ${t.project} | ${t.priority} | ${t.status} | ${t.assignee}`))
        break
      case 'Equipment Utilization':
        lines.push('EQUIPMENT:')
        equipment.forEach(e => lines.push(`  ${e.name} | ${e.category} | ${e.status} | ${e.assignedTo} | ${e.location}`))
        break
      case 'Project Summary':
        lines.push('PROJECTS:')
        projects.forEach(p => lines.push(`  ${p.name} | ${p.client} | ${p.manager} | ${p.status} | Budget: $${p.budget.toLocaleString()} | Spent: $${p.spent.toLocaleString()} | Progress: ${p.progress}%`))
        lines.push('')
        lines.push(`Total Projects: ${projects.length}`)
        lines.push(`Total Budget: $${projects.reduce((s, p) => s + p.budget, 0).toLocaleString()}`)
        lines.push(`Total Spent: $${projects.reduce((s, p) => s + p.spent, 0).toLocaleString()}`)
        break
    }
    const content = lines.join('\n')
    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url; a.download = report.type.replace(/\s+/g, '_') + '.txt'; a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h2 className="text-2xl font-bold text-slate-900">Reports</h2>
          <p className="text-slate-500">Generate and download financial, operational, and team reports.</p>
        </div>
        <button onClick={() => setShowGenerate(true)} className="bg-[#191970] hover:bg-[#121258] text-white px-4 py-2 rounded-lg font-medium text-sm transition-colors shadow-sm flex items-center gap-2">
          <FileText className="w-4 h-4" /> Generate Report
        </button>
      </div>

      {showGenerate && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40" onClick={() => setShowGenerate(false)}>
          <div className="bg-white rounded-2xl shadow-2xl w-full max-w-md mx-4 p-6" onClick={e => e.stopPropagation()}>
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-lg font-semibold text-slate-900">Generate Report</h3>
              <button onClick={() => setShowGenerate(false)} className="p-2 hover:bg-slate-100 rounded-lg transition-colors">
                <X className="w-5 h-5 text-slate-400" />
              </button>
            </div>
            <p className="text-sm text-slate-500 mb-4">Select report type to generate:</p>
            <div className="space-y-2">
              {reportTypes.map((rt, i) => {
                const Icon = rt.icon
                return (
                  <button key={i} onClick={() => generateReport(rt.title)} className="w-full flex items-center gap-3 p-3 rounded-lg border border-slate-200 hover:border-indigo-300 hover:bg-indigo-50 transition-all text-left">
                    <div className={cn('p-2 rounded-lg', rt.iconBg)}>
                      <Icon className={cn('w-5 h-5', rt.iconColor)} />
                    </div>
                    <div>
                      <p className="text-sm font-medium text-slate-900">{rt.title}</p>
                      <p className="text-xs text-slate-500">{rt.format}</p>
                    </div>
                  </button>
                )
              })}
            </div>
          </div>
        </div>
      )}

      {recentReports.length === 0 ? (
        <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-12 text-center">
          <FileText className="w-12 h-12 mx-auto mb-3 text-slate-300" />
          <h3 className="text-lg font-semibold text-slate-900 mb-1">No Reports Generated</h3>
          <p className="text-sm text-slate-500">Generate reports from the Recent Reports section to see them here.</p>
        </div>
      ) : (
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {reportTypes.map((report, i) => {
          const Icon = report.icon
          const lastGen = recentReports
            .filter(r => r.type === report.title)
            .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())[0]
          return (
            <div key={i} className="bg-white p-5 rounded-xl border border-slate-200 shadow-sm hover:shadow-md transition-shadow">
              <div className="flex items-start justify-between mb-4">
                <div className={cn('p-2.5 rounded-lg', report.iconBg)}>
                  <Icon className={cn('w-5 h-5', report.iconColor)} />
                </div>
                <span className="text-xs font-medium text-slate-400 bg-slate-100 px-2 py-1 rounded">{report.format}</span>
              </div>
              <h3 className="text-base font-semibold text-slate-900 mb-1">{report.title}</h3>
              <p className="text-sm text-slate-500 mb-4 line-clamp-2">{report.description}</p>
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-1.5 text-xs text-slate-400">
                  <Clock className="w-3.5 h-3.5" />
                  {lastGen ? lastGen.date : 'Not generated'}
                </div>
                {lastGen ? (
                  <div className="flex gap-2">
                    <button onClick={() => handleDownload(lastGen)} className="flex items-center gap-1.5 text-sm font-medium text-indigo-600 hover:text-indigo-700 transition-colors">
                      <Download className="w-4 h-4" />
                      Download
                    </button>
                    <button onClick={() => generateReport(report.title)} className="flex items-center gap-1.5 text-sm font-medium text-amber-600 hover:text-amber-700 transition-colors">
                      <FileText className="w-4 h-4" />
                      Generate
                    </button>
                  </div>
                ) : (
                  <button onClick={() => generateReport(report.title)} className="flex items-center gap-1.5 text-sm font-medium text-indigo-600 hover:text-indigo-700 transition-colors">
                    <FileText className="w-4 h-4" />
                    Generate
                  </button>
                )}
              </div>
            </div>
          )
        })}
      </div>
      )}

      <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
        <div className="p-6 border-b border-slate-200">
          <h3 className="text-lg font-semibold text-slate-900">Recent Reports</h3>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-slate-50 text-slate-500 text-xs uppercase tracking-wider">
                <th className="p-4 font-medium">Report Type</th>
                <th className="p-4 font-medium">Date</th>
                <th className="p-4 font-medium">Generated By</th>
                <th className="p-4 font-medium">Status</th>
                <th className="p-4 font-medium">Format</th>
                <th className="p-4 font-medium text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200">
              {recentReports.length === 0 ? (
                <tr>
                  <td colSpan={6} className="p-8 text-center text-slate-400">
                    <FileText className="w-8 h-8 mx-auto mb-2 opacity-50" />
                    <p className="text-sm font-medium">No reports generated yet</p>
                    <p className="text-xs mt-1">Generate a report above to see it here.</p>
                  </td>
                </tr>
              ) : recentReports.map((report) => (
                <tr key={report.id} className="hover:bg-slate-50 transition-colors group">
                  <td className="p-4">
                    <div className="flex items-center gap-2">
                      <FileText className="w-4 h-4 text-slate-400" />
                      <span className="font-medium text-slate-900">{report.type}</span>
                    </div>
                  </td>
                  <td className="p-4 text-sm text-slate-600">{report.date}</td>
                  <td className="p-4 text-sm text-slate-600">{report.generatedBy}</td>
                  <td className="p-4">
                    <div className="flex items-center gap-1.5">
                      <div className={cn('w-2 h-2 rounded-full', report.status === 'Generated' ? 'bg-emerald-500' : 'bg-rose-500')} />
                      <span className={cn('text-xs font-medium px-2 py-0.5 rounded-full', report.status === 'Generated' ? 'bg-emerald-50 text-emerald-700' : 'bg-rose-50 text-rose-700')}>
                        {report.status}
                      </span>
                    </div>
                  </td>
                  <td className="p-4">
                    <span className="text-xs font-medium text-slate-500 bg-slate-100 px-2 py-1 rounded">{report.format}</span>
                  </td>
                  <td className="p-4 text-right relative">
                    <div className="flex items-center justify-end gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                      <button onClick={() => handleDownload(report)} className="p-1.5 text-slate-400 hover:text-indigo-600 hover:bg-indigo-50 rounded-lg transition-colors">
                        <Download className="w-4 h-4" />
                      </button>
                      <button onClick={() => setOpenMenuId(openMenuId === report.id ? null : report.id)} className="p-1.5 text-slate-400 hover:text-slate-600 hover:bg-slate-100 rounded-lg transition-colors">
                        <MoreVertical className="w-4 h-4" />
                      </button>
                    </div>
                    {openMenuId === report.id && (
                      <div className="absolute right-4 top-10 bg-white rounded-lg shadow-lg border border-slate-200 py-1 z-10 min-w-[120px]">
                        <button onClick={() => handleDelete(report.id)} className="flex items-center gap-2 w-full px-3 py-2 text-sm text-rose-600 hover:bg-rose-50">
                          <Trash2 className="w-3.5 h-3.5" /> Delete
                        </button>
                      </div>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  )
}
